name: Run print.py every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prints
        run: python print.py