name: Run print.py every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prints
        run: python print.py

      - name: Commit changes
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git add .
          git commit -m "Automated commit of print.py output"
          git push