name: Run print.py every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make Changes
        run: echo "print("Hello world")" > print.py    

      - name: Prints
        run: python print.py 


      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add .
          git commit -m "Automated commit of print.py output"
          git push
